import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';

// Match the DTO structure from Java
export interface Party {
  id: number;
  name: string;
  shopName: string;
  city: string;
  contact: string;
  stats: {
    totalBuy: number;
    totalSell: number;
    pendingAmount: number;
  };
}

export interface UnsettledTransaction {
  id: number;
  date: string;
  description: string;
  pendingAmount: number;
  isSelected?: boolean;
  settleAmount?: number; // NEW: Partial settlement amount
}

@Injectable({
  providedIn: 'root'
})
export class PartyService {
  
  // Point to your Spring Boot API
  private apiUrl = 'http://localhost:8081/api/parties'; 

  constructor(private http: HttpClient) { }

  // --- READ ---
  getParties(): Observable<Party[]> {
    return this.http.get<Party[]>(this.apiUrl);
  }

  // --- CREATE ---
  // We accept Partial<Party> because ID and Stats are generated by Backend
  addParty(party: Partial<Party>): Observable<Party> {
    return this.http.post<Party>(this.apiUrl, party);
  }

  // --- UPDATE ---
  updateParty(id: number, party: Partial<Party>): Observable<Party> {
    return this.http.put<Party>(`${this.apiUrl}/${id}`, party);
  }

  // --- DELETE ---
  deleteParty(id: number): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/${id}`);
  }

  // --- GET UNSETTLED ITEMS FOR A PARTY ---
  getUnsettledHistory(partyId: number): Observable<UnsettledTransaction[]> {
    // REAL API (Uncomment when backend is ready):
    // return this.http.get<UnsettledTransaction[]>(`${this.apiUrl}/${partyId}/unsettled`);
    
    // MOCK DATA FOR TESTING (Remove this after backend is ready)
    return of(this.getMockUnsettledData(partyId));
  }

  // HELPER: Mock Unsettled Data Generator
  private getMockUnsettledData(partyId: number): UnsettledTransaction[] {
    // Generate different mock data based on partyId
    if (partyId === 1) {
      return [
        { id: 101, date: '2026-01-15', description: 'Gold Purchase (10g)', pendingAmount: 5000 },
        { id: 102, date: '2026-01-22', description: 'Silver Inward (500g)', pendingAmount: -12000 },
        { id: 103, date: '2026-02-01', description: 'Cash Advance', pendingAmount: 3000 },
        { id: 104, date: '2026-01-22', description: 'Silver Inward (200g)', pendingAmount: -3000 },
        { id: 105, date: '2026-01-22', description: 'Silver Inward (300g)', pendingAmount: 6000 }
      ];
    } else if (partyId === 2) {
      return [
        { id: 201, date: '2026-01-10', description: 'Old Stock Settlement', pendingAmount: -8000 },
        { id: 202, date: '2026-01-28', description: 'Partial Payment', pendingAmount: 2000 }
      ];
    }
    
    // No unsettled items for other parties
    return [];
  }
}
